### PR TITLE
Update to support `fork-ts-checker-webpack-plugin` v5

### PR DESCRIPTION
**Pull request by sanex3339**
https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin/issues/36

### CODE REVIEW

**Comment by sanex3339** [comment]
It is still WIP!!!

**Comment by sanex3339** [comment]
Looks like now it works

**Comment by sanex3339** [comment]
@johnnyreilly  check this, please.

**Review by johnnyreilly — APPROVED** [review]
This looks great! Thanks so much for doing this! 

Have you tested this out on your own projects?

**Comment by sanex3339** [comment]
I have tested it. It showed notification only for the second and following compilations (fast incremental compilation in watch mode).
It didn't show notification for the initial compilation (full compilation from the scratch)

**Comment by johnnyreilly** [comment]
Interesting! I wonder if that's down to a deliberate behaviour choice in `fork-ts-checker-webpack-plugin` v5. @piotr-oles - does the `Issues` event only get triggered after initial compilation in v5?

**Comment by sanex3339** [comment]
I'm not sure how it works, but the first compilation even with the errors doesn't show notification
image

**Comment by sanex3339** [comment]
And the second incremental compilation works fine
image

**Comment by sanex3339** [comment]
Ah. It is because i have an option:
```
skipFirstNotification: true
```

**Comment by sanex3339** [comment]
Yes, without this option it runs fine on the first compilation too

**Comment by johnnyreilly** [comment]
Awesome!

**Comment by piotr-oles** [comment]
😄 

I think you should also update README.md as it states that minimum version of fork-ts-checker-webpack-plugin is 4, but it should be 5 starting from this commit :)

**Comment by johnnyreilly** [comment]
Is there anymore to do, or are we ready to ship?

**Comment by johnnyreilly** [comment]
Oh yes! Could you update the readme please!

**Comment by sanex3339** [comment]
@johnnyreilly done

**Comment by johnnyreilly** [comment]
Shall we ship?

**Comment by sanex3339** [comment]
I think yes

**Comment by johnnyreilly** [comment]
https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin/releases/tag/v3.0.0

It's live! Thanks for the help! 🌻❤️

**Pull request merged**
