### PR TITLE
Edit README, wrap hooks in try/catch

### PR DESCRIPTION
**Pull request by Rolandisimo**
Add info about hook fails in README, update steps, wrap hooks in try/catch with an explanatory error message

### CODE REVIEW

**Review by johnnyreilly — COMMENTED** [review]
Nice - could you update the `changelog` and the `package.json` as well please?

**Comment by Rolandisimo** [comment]
Oh, sure. This would be 0.6.1 I guess?

**Comment by johnnyreilly** [comment]
Works for me!

**Comment by Rolandisimo** [comment]
Please recheck. Feels weird to praise meself in the changelog, but oh well 😄

**Comment by johnnyreilly** [comment]
Oh you deserve it!

**Comment by johnnyreilly** [comment]
https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin/releases/tag/v0.6.1

**Pull request merged**
