### PR TITLE
Include index.d.ts in NPM package.

### PR DESCRIPTION
**Pull request by cdeutsch**

### CODE REVIEW

**Comment by cdeutsch** [comment]
Let me know if I should bump the version in the package.json as well.

**Comment by johnnyreilly** [comment]
Please. v1.0.0 I guess. Can you add an entry to the changelog too please? Don't forget to thank yourself! 😁

**Comment by cdeutsch** [comment]
Updated 👍

**Comment by johnnyreilly** [comment]
thanks!

**Comment by johnnyreilly** [comment]
Should be available on npm now

**Pull request merged**
