### PR TITLE
Update fork-ts-checker-webpack-plugin to v8

### PR DESCRIPTION
**Pull request by TrevorSayre**
Similar to https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin/pull/57, this is intended as a breaking change to support the latest v8 of [fork-ts-checker-webpack-plugin](https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/releases/tag/v8.0.0).

While doing so, I also noticed several packages were also out of date and didn't require any logic changes to the code.

The one major change for developers is that [tslint](https://palantir.github.io/tslint/) has been deprecated since 2019 and it is recommended to use [typescript-eslint](https://typescript-eslint.io/getting-started), so I have also migrated to this solution.

The overall goal of this PR is to bring the whole package up to date, but the only meaningful change to consumers is that it now supports fork-ts-checker-webpack-plugin at v8.

Tests pass (`yarn test`) and the build is successful (`yarn build`).

### CODE REVIEW

**Comment by johnnyreilly** [comment]
Do you want to drop support for node 12 with this? It's EOL

**Comment by TrevorSayre** [comment]
@johnnyreilly I think that might be a good idea

**Comment by TrevorSayre** [comment]
Updated the GitHub push and release workflows to use Node 14

**Comment by TrevorSayre** [comment]
Updated the Dockerfile to use Node 14

**Comment by TrevorSayre** [comment]
@johnnyreilly Should be all set 👍 Happy to address any other thoughts

**Comment by johnnyreilly** [comment]
Sorry forgot about this. Workflows running

**Comment by TrevorSayre** [comment]
@johnnyreilly No worries, real life comes first, none of this is super important. Thanks for the attention. Looks like checks are passing, let me know if there is anything more I can do 🙏

**Comment by TrevorSayre** [comment]
Thanks for all your help, @johnnyreilly, is there anything else to be done to move this forward?

**Comment by TrevorSayre** [comment]
Hey @johnnyreilly, just a weekly check-in, hope all is well 👍

**Comment by johnnyreilly** [comment]
Sorry about that - merged

**Comment by johnnyreilly** [comment]
I'm really sorry about the time this had taken - I've added you as a collaborator. Should you want to help again you'll be able to move faster. Fine work on this. ❤️🌻

**Comment by TrevorSayre** [comment]
@johnnyreilly Real life always comes first, no worries at all about any delays. Thanks for all your work! I appreciate the invitation to collaborate. Sadly the invitation expired. Will you be able to release the latest version?

**Comment by johnnyreilly** [comment]
Sent invite again - will do release https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin/actions/runs/5030478898

**Pull request merged**
