### PR TITLE
Fix all npm audit issues

### LINKED ISSUE #52: Upgrade node-notifier or make it a peer dependency
### Expected Behaviour
`node-notifier` needs to be updated to 8.0.1 or later to address: https://github.com/advisories/GHSA-5fw9-fq32-wv5p
Or it could probably be made a peer dependency.

### Actual Behaviour
Depends on version less than 8.0.1

### Steps to Reproduce the Problem
run `npm audit` in package dependent on `fork-ts-checker-notifier-webpack-plugin`

### PR DESCRIPTION
**Pull request by hisuwh**
Fixes #52 

Addressed all npm audit issues whilst I was here.

`npm run build` didn't work for me on master.  But `npm test` passed before and after these changes.

### CODE REVIEW

**Comment by johnnyreilly** [comment]
It looks like the build is failing - we won't be able to merge a failing build I'm afraid

**Comment by hisuwh** [comment]
@johnnyreilly as I said "npm run build didn't work for me on master".

Any suggestions?  This is the error I got:

```
$ npm run build

> fork-ts-checker-notifier-webpack-plugin@4.0.0 build C:\code\fork-ts-checker-notifier-webpack-plugin
> tsc --version && tsc

Version 3.9.10
node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:4:61 - error TS2694: Namespace 'exports' has no exported member 'Plugin'.

4 declare class ForkTsCheckerWebpackPlugin implements webpack.Plugin {
                                                              ~~~~~~

node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:21:113 - error TS2694: Namespace 'exports' has no exported member 'compilation'.

21         start: import("tapable").AsyncSeriesWaterfallHook<import("./reporter/FilesChange").FilesChange, webpack.compilation.Compilation, any>;
                                                                                                                   ~~~~~~~~~~~

node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:22:53 - error TS2694: Namespace 'exports' has no exported member 'compilation'.

22         waiting: import("tapable").SyncHook<webpack.compilation.Compilation, any, any>;
                                                       ~~~~~~~~~~~

node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:23:54 - error TS2694: Namespace 'exports' has no exported member 'compilation'.

23         canceled: import("tapable").SyncHook<webpack.compilation.Compilation, any, any>;
                                                        ~~~~~~~~~~~

node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:24:58 - error TS2694: Namespace 'exports' has no exported member 'compilation'.

24         error: import("tapable").SyncHook<Error, webpack.compilation.Compilation, any>;
                                                            ~~~~~~~~~~~

node_modules/fork-ts-checker-webpack-plugin/lib/ForkTsCheckerWebpackPlugin.d.ts:25:94 - error TS2694: Namespace 'exports' has no exported member 'compilation'.

25         issues: import("tapable").SyncWaterfallHook<import("./issue/Issue").Issue[], webpack.compilation.Compilation | undefined, void>;
                                                                                                ~~~~~~~~~~~


Found 6 errors.
```

**Comment by johnnyreilly** [comment]
You've used npm to do the upgrade. This project uses yarn. Might be worth reattempting the change with yarn

**Comment by cdeutsch** [comment]
Can this be landed? Dealing with the security issues as well

**Comment by johnnyreilly** [comment]
Sorry I forgot about this - yeah we should land this.  Do you want to update the version in the `package.json` and add an entry to the `CHANGELOG.md` please?  I'll then look to merge and ship

**Comment by hisuwh** [comment]
@johnnyreilly done

**Comment by hisuwh** [comment]
@johnnyreilly done

**Review by cdeutsch — APPROVED** [review]

**Review by johnnyreilly — APPROVED** [review]

**Comment by johnnyreilly** [comment]
Released with https://github.com/johnnyreilly/fork-ts-checker-notifier-webpack-plugin/releases/tag/v5.0.0

Apologies for the delay and thanks for contributing!

**Pull request merged**
